services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - nest_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  nest_data: {}
